apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 496116343239.dkr.ecr.ap-northeast-3.amazonaws.com/myapp-repo
  newName: 496116343239.dkr.ecr.ap-northeast-3.amazonaws.com/myapp-repo
  newTag: aa68ef2e
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
